### ISSUE TITLE
Issue with rot47

### ISSUE THREAD

**Issue by cargonfun** [prodigiousMind/blizzardwrap#1]

**Comment by prodigiousMind** [comment]
The issue you encountered is due to the use of "`" backtick.
In bash, backtick ' ` ' can be used to substitute commands as with $(), $(command)
such as `ls -la` or $(ls -la)
Since, the input string (encoded string) contains backticks, bash, interpreted it as a command. In order to get the correct input you need to escape it using backslash(es).
For example:
"\"" -> double quote inside double quotes can be escaped using backslash
'\'' -> Single quote inside single quotes escaped by a backslash
